### ISSUE TITLE
How to solve the "the specified shard ID does not exist in proxy's configuration"

### ISSUE THREAD

**Issue by Jackwumingjie** [multiversx/mx-chain-proxy-go#378]
My nodes:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/39093109/227907501-ddb329f2-b5ec-42e3-9fbd-e2ef1a2dd682.png">
My proxy config:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/39093109/227907642-eb377cf7-4930-4779-9e7f-78c33cddcaa9.png">
The proxy log:
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/39093109/227907739-39dfedb1-310b-4c8c-8ead-2f66686aa790.png">
The two apis:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/39093109/227908185-0489d535-c911-4ec0-9c67-ddc71c34051b.png">
How to config the "specified shard ID"?

**Comment by schimih** [comment]
Hey @Jackwumingjie ,
I believe we discussed on discord as well. Why don't you use an observing squad?

**Comment by schimih** [comment]
Discussion taken to discord: https://discord.com/channels/1045353153073258557/1088114361094115328/1090207570163142656
Invitation: https://discord.gg/multiversxbuilders
